### ISSUE TITLE
我编译内核总是报错

### ISSUE THREAD

**Issue by Angel0726** [XayahSuSuSu/kernel_redmi_mt6885#1]
https://github.com/Angel0726/andriod_kernel/blob/main/k30_ultra.md。我的编译教程

**Comment by XayahSuSuSu** [comment]
Clang 11 测试时没有问题，Clang12需要自行修复一些地方

**Comment by Angel0726** [comment]
> Clang 11 测试时没有问题，Clang12需要自行修复一些地方

这么说clang不是向下兼容的呀

**Comment by Angel0726** [comment]
> Clang 11 测试时没有问题，Clang12需要自行修复一些地方

支持andriod R miui12吗？

**Comment by XayahSuSuSu** [comment]
> > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> 
> 支持andriod R miui12吗？

尚未测试，类原生A12测试可用

**Comment by Angel0726** [comment]
> > > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> > 
> > 支持andriod R miui12吗？
> 
> 尚未测试，类原生A12测试可用

编译了内核，驱动程序是不是需要重新编译

**Comment by XayahSuSuSu** [comment]
> > > > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> > > 
> > > 
> > > 支持andriod R miui12吗？
> > 
> > 
> > 尚未测试，类原生A12测试可用
> 
> 编译了内核，驱动程序是不是需要重新编译

内核模块已经built-in

**Comment by Angel0726** [comment]
> > > > > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> > > > 
> > > > 
> > > > 支持andriod R miui12吗？
> > > 
> > > 
> > > 尚未测试，类原生A12测试可用
> > 
> > 
> > 编译了内核，驱动程序是不是需要重新编译
> 
> 内核模块已经built-in

android R? 这个跟[原版本](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cezanne-r-oss)有什么区别吗？
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cezanne-r-oss

**Comment by Angel0726** [comment]
> > > > > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> > > > 
> > > > 
> > > > 支持andriod R miui12吗？
> > > 
> > > 
> > > 尚未测试，类原生A12测试可用
> > 
> > 
> > 编译了内核，驱动程序是不是需要重新编译
> 
> 内核模块已经built-in
```shell
make[3]: *** No rule to make target 'net/netfilter/xt_TCPMSS.o', needed by 'net/netfilter/built-in.o'.  Stop.
```
将上述 `net/netfilter/xt_tcpmss.c`修改为`net/netfilter/xt_TCPMSS.c`之后。上面的报错没有了，但是出现了下面的错误
```shell
ld.lld: error: duplicate symbol: mtk_vcu_get_page
>>> defined at slab.h:522 (/home/kernel_redmi_mt6885/out/../include/linux/slab.h:522)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_get_page) in archive built-in.o
>>> defined at slab.h:522 (/home/kernel_redmi_mt6885/out/../include/linux/slab.h:522)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0x748) in archive built-in.o

ld.lld: error: duplicate symbol: mtk_vcu_free_buffer
>>> defined at mtk_vcodec_mem.c:251 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:251)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_free_buffer) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:251 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:251)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0x850) in archive built-in.o

ld.lld: error: duplicate symbol: mtk_vcu_free_page
>>> defined at mtk_vcodec_mem.c:302 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:302)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_free_page) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:302 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:302)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xA0C) in archive built-in.o

ld.lld: error: duplicate symbol: mtk_vcu_buffer_ref_dec
>>> defined at mtk_vcodec_mem.c:337 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:337)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_buffer_ref_dec) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:337 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:337)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xB24) in archive built-in.o

ld.lld: error: duplicate symbol: vcu_io_buffer_cache_sync
>>> defined at mtk_vcodec_mem.c:356 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:356)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_io_buffer_cache_sync) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:356 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:356)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xBD0) in archive built-in.o

ld.lld: error: duplicate symbol: vcu_buffer_flush_all
>>> defined at mtk_vcodec_mem.c:371 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:371)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_buffer_flush_all) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:371 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:371)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xC7C) in archive built-in.o

ld.lld: error: duplicate symbol: vcu_buffer_cache_sync
>>> defined at mtk_vcodec_mem.c:407 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:407)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_buffer_cache_sync) in archive built-in.o
>>> defined at mtk_vcodec_mem.c:407 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:407)
>>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xDCC) in archive built-in.o
make[1]: *** [/home/kernel_redmi_mt6885/Makefile:1144: vmlinux] Error 1
```

**Comment by XayahSuSuSu** [comment]
> > > > > > Clang 11 测试时没有问题，Clang12需要自行修复一些地方
> > > > > 
> > > > > 
> > > > > 支持andriod R miui12吗？
> > > > 
> > > > 
> > > > 尚未测试，类原生A12测试可用
> > > 
> > > 
> > > 编译了内核，驱动程序是不是需要重新编译
> > 
> > 
> > 内核模块已经built-in
> 
> ```shell
> make[3]: *** No rule to make target 'net/netfilter/xt_TCPMSS.o', needed by 'net/netfilter/built-in.o'.  Stop.
> ```
> 
> 将上述 `net/netfilter/xt_tcpmss.c`修改为`net/netfilter/xt_TCPMSS.c`之后。上面的报错没有了，但是出现了下面的错误
> 
> ```shell
> ld.lld: error: duplicate symbol: mtk_vcu_get_page
> >>> defined at slab.h:522 (/home/kernel_redmi_mt6885/out/../include/linux/slab.h:522)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_get_page) in archive built-in.o
> >>> defined at slab.h:522 (/home/kernel_redmi_mt6885/out/../include/linux/slab.h:522)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0x748) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: mtk_vcu_free_buffer
> >>> defined at mtk_vcodec_mem.c:251 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:251)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_free_buffer) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:251 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:251)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0x850) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: mtk_vcu_free_page
> >>> defined at mtk_vcodec_mem.c:302 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:302)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_free_page) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:302 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:302)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xA0C) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: mtk_vcu_buffer_ref_dec
> >>> defined at mtk_vcodec_mem.c:337 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:337)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(mtk_vcu_buffer_ref_dec) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:337 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:337)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xB24) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: vcu_io_buffer_cache_sync
> >>> defined at mtk_vcodec_mem.c:356 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:356)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_io_buffer_cache_sync) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:356 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:356)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xBD0) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: vcu_buffer_flush_all
> >>> defined at mtk_vcodec_mem.c:371 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:371)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_buffer_flush_all) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:371 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:371)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xC7C) in archive built-in.o
> 
> ld.lld: error: duplicate symbol: vcu_buffer_cache_sync
> >>> defined at mtk_vcodec_mem.c:407 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:407)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(vcu_buffer_cache_sync) in archive built-in.o
> >>> defined at mtk_vcodec_mem.c:407 (/home/kernel_redmi_mt6885/out/../drivers/media/platform/mtk-vcu/mtk_vcodec_mem.c:407)
> >>>            drivers/media/platform/mtk-vcu/mtk_vcodec_mem.o:(.text+0xDCC) in archive built-in.o
> make[1]: *** [/home/kernel_redmi_mt6885/Makefile:1144: vmlinux] Error 1
> ```

Clang版本是？

**Comment by Angel0726** [comment]
> Clang版本是？

clang 11       clang-r383902      . 用的docker还有wsl2都有问题。问一下联发科内核可以使用kvm吗？
